name: build_deploy_package_production

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build_deploy_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Install Node.js to latest version LTS and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image - Production version latest
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: corentin35/flapi-cms-common:latest

      - name: Build and push Docker image - Production version x.x.x
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: corentin35/flapi-cms-common:${{ steps.previoustag.outputs.tag }}

      - name: Replace image tag in deployment.yaml for Kubernetes
        run: |
          sed -i 's/\${TAG_VERSION}/'${{ steps.previoustag.outputs.tag }}'/g' k8s/production/deployment.yaml

      - name: Connect to the cluster K3S for deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: |
            apply -f k8s/production/namespace.yaml
            -f k8s/production/certificate.yaml
            -f k8s/production/docker-registry-secret.yaml
            -f k8s/production/deployment.yaml
            -f k8s/production/ingress.yaml
            -f k8s/production/service.yaml

      - name: Build project
        run: npm run build

      - name: Publish package to registry npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
